### ISSUE TITLE
lein vertx is ignoring my VERTX_OPTS how do a remote debug?

### ISSUE THREAD

**Issue by cocodrino** [isaiah/lein-vertx#23]
Hi, when I wish to do a remote debug I set the VERTX_OPTS, something like this

```
 "-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=4000,server=y,suspend=n"
```

unfortunately seems than when I run using lein vertx these options are ignored, so my question is which could be the best option for set the debugger params?..must add it inside my lein project file??

thanks

**Comment by tobias** [comment]
`VERTX_OPTS` is only read by the vertx shell script to set up jvm options. When using lein, you'll need to set them via `:jvm-opts` in `project.clj`. Try:

```
:jvm-opts ["-Xdebug" "-Xnoagent" "-Djava.compiler=NONE" "-Xrunjdwp:transport=dt_socket,address=4000,server=y,suspend=n"]
```

**Comment by cocodrino** [comment]
hi tobias, seems not works for me...I create a new lein vertx project and append the line to my project.clj

like this:

``` clojure
 (defproject remotedbgr "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]]
  :plugins [[lein-vertx "0.3.1"]]
  :jvm-opts ["-Xdebug" "-Xnoagent" "-Djava.compiler=NONE" "-Xrunjdwp:transport=dt_socket,address=4000,server=y,suspend=n"]
  :vertx {:main remotedbgr.core/init
          :author "FIXME: Your name"
          :keywords ["FIXME: keywords"]
          :developers ["FIXME: other developers"]})


```

I run with lein vertx run and this is the output

``` bash
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Started clojure verticle: RemotedbgrCoreInit.clj 
Succeeded in deploying verticle 
I'm working!
I'm working!
I'm working!
I'm working!
I'm working!
^C%          

```

doesnt show any info about remote debug, if I try connect my debugger I get refused connection

**Comment by cocodrino** [comment]
I forget add than even executing 

export JAVA_OPTS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=4000,server=y,suspend=n"

before running lein vertx this seems not works...

**Comment by tobias** [comment]
Ah, the plugin calls out to java directly, so there currently is not way to provide additional arguments to the call (see https://github.com/isaiah/lein-vertx/blob/master/src/lein_vertx/core.clj#L72). I think to debug you'll need to use the vertx command directly (without lein), or modify lein-vertx to set those options (or honor an env var and set them).

**Comment by cocodrino** [comment]
thanks tobias..at the end I'd to change my _JAVA_OPTIONS variable...not elegant but it works ok :D.....
